hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "metrics.json"
model_name: "ViT-B/16"
prompt_template: "a bad photo of a {}."

batch_size: 128
initial_increment: 100  
increment: 5
scenario: "class"
dataset: "tinyimagenet"
